source /opt/ros/galactic/setup.bash
source ../ROS2/common_interfaces/install/local_setup.bash
source ../ROS2/vision_opencv/install/local_setup.bash
export ROS1_INSTALL_PATH=/opt/ros/noetic
export ROS2_INSTALL_PATH=/opt/ros/galactic
source ../ROS2/image_common/install/setup.bash
source ../ROS2/ament_lint/install/setup.bash
source ../ROS2/vision_msgs/install/setup.bash
source ../ROS2/april_msgs/install/setup.bash